name: adaptive_location_tracker_example
description: Example app for the adaptive_location_tracker package.
publish_to: none
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  adaptive_location_tracker:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
